Vagrant.configure("2") do |config|
    num = 1
	type = "ubuntu-16"
    (1..num).each do |i|
        guest_ip_num = 10 + i
        guest_ip = "192.168.69.#{guest_ip_num}"
        port_num = 2230 + i
		name = "#{type}-node#{i}"
        config.vm.define "#{name}" do |node|
            # 设置虚拟机的Box
            node.vm.box = "ubuntu/xenial64"
            # 设置虚拟机的主机名
            node.vm.hostname = "node#{i}"
            # 设置虚拟机的IP
            node.vm.network "private_network", ip: "#{guest_ip}"
            # 设置端口映射
            config.vm.network "forwarded_port", id: "ssh", guest: 22, host: "#{port_num}".to_i, host_ip: "127.0.0.1", auto_correct: true
            # 设置主机与虚拟机的共享目录
            node.vm.synced_folder "./vagrant_shared_folder", "/home/vagrant/share"
            # VirtaulBox相关配置
            node.vm.provider "virtualbox" do |v|
                # 设置虚拟机的名称
                v.name = "#{name}"
                # 设置虚拟机的内存大小
                v.memory = 2048
                # 设置虚拟机的CPU个数
                v.cpus = 2
            end

            # 使用shell脚本进行软件安装和配置
            config.vm.provision "shell", path: "bootstrap.sh"
            #node.vm.provision "shell", inline: <<-SHELL
            #    apt-get update
            #SHELL
        end
    end
end

